name: Build and test

on: [push, pull_request]

env:
  CI: true

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm run test:format
      - run: npm run test:lint
      - run: npm test
      - run: npm run send-coverage
